version: '3.7'
services:
  void:
    build:
      context: .
    logging:
      driver: journald
    ports:
      - '23666:23666'
    restart: unless-stopped
    volumes:
      - state:/var/lib/void
volumes:
  state:
